### ISSUE TITLE
initmodel

### ISSUE THREAD

**Issue by zxmyyds** [LeileiCao/ProtoFormer#1]
I cant find it can you help me

**Comment by LeileiCao** [comment]
You can creat a folder named "initmodel".

**Comment by zxmyyds** [comment]
@LeileiCao Thank you for your quick reply but 
![1681385597396](https://user-images.githubusercontent.com/103728486/231746287-020a4dc2-ba75-481e-808d-3eb4fd8830fd.png)
classes has problem  
Can I comment it out

**Comment by zxmyyds** [comment]
my email is 1627254693@qq.com If it is convenient for you, contact information is sent directly to my email  I add you

**Comment by LeileiCao** [comment]
ok
